# Generated by Django 5.0.2 on 2024-02-08 17:38

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('related_links', models.CharField(max_length=50)),
                ('review_description', models.TextField()),
                ('additional_comments', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('dark_patterns', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Basket Sneaking'), (2, 'Interface Interference'), (3, 'Nagging'), (4, 'False Urgency'), (5, 'Confirm Shaming'), (6, 'Subscription Tags'), (7, 'Forced Action'), (8, 'Disguised Ads'), (9, 'Bait and Switch'), (10, 'Other')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Approved',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='DarkPatterns',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'DarkPatterns',
            },
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('related_links', models.CharField(max_length=50)),
                ('review_description', models.TextField()),
                ('additional_comments', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('dark_patterns', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Basket Sneaking'), (2, 'Interface Interference'), (3, 'Nagging'), (4, 'False Urgency'), (5, 'Confirm Shaming'), (6, 'Subscription Tags'), (7, 'Forced Action'), (8, 'Disguised Ads'), (9, 'Bait and Switch'), (10, 'Other')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Pending',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=30)),
                ('review_count', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.company')),
            ],
        ),
    ]
