# Generated by Django 5.0.2 on 2024-02-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='dark_patterns',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pending',
            name='dark_patterns',
            field=models.CharField(max_length=10),
        ),
    ]
