# Generated by Django 5.0.2 on 2024-02-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approved',
            options={'verbose_name_plural': 'Approved'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name_plural': 'Consumers'},
        ),
        migrations.AlterModelOptions(
            name='pending',
            options={'verbose_name_plural': 'Pending'},
        ),
    ]
